vich_uploader:
  db_driver: orm
  mappings:
    noticia_images:
      uri_prefix: '%app.path.noticia_images%'
      upload_destination: '%kernel.project_dir%/public%app.path.noticia_images%'
      namer:
        service: vich_uploader.namer_uniqid
      inject_on_load:     false
      delete_on_update:   true
      delete_on_remove:   true
    
    documentos_image:
      uri_prefix: '%app.path.documento_images%'
      upload_destination: '%kernel.project_dir%/public%app.path.documento_images%'
      namer:
        service: vich_uploader.namer_uniqid
      inject_on_load:     false
      delete_on_update:   true
      delete_on_remove:   true