vich_uploader:
  db_driver: orm
  mappings:
    # banner_images:
    #   uri_prefix: '%app.path.banner_images%'
    #   upload_destination: '%kernel.project_dir%/public%app.path.banner_images%'
    # programa_images:
    #   uri_prefix: '%app.path.programa_images%'
    #   upload_destination: '%kernel.project_dir%/public%app.path.programa_images%