easy_admin:
  design:
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
      - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
    # van assets
    menu:
      - label: 'ChacoTv'
      - {label: 'Panel Principal', route: 'admin_dashboard', icon: 'caret-down', default: true }
      - {label: 'Noticias' , entity: 'Noticia', icon: 'indent' }
      # - {label: 'Video En Vivo' , entity: 'VideoEnVivo', icon: 'indent' }
      # - {label: 'Programacion' , route: 'new_programming', icon: 'indent' }
      # - {label: 'Banner' , entity: 'Banner', icon: 'indent' }
      # - {label: 'Video' , entity: 'Video', icon: 'indent' }
      - {label: 'Programa' , entity: 'Programa', icon: 'indent' }
      # - {label: 'Capitulos' , entity: 'Capitulo', icon: 'indent' }