easy_admin:
  site_name: '<div><img src="/images/logo_chacotv.png" /><img style="max-height:30px; max-width:150px;" src="/images/logo_ecom.png" /></div>'
  design:
    form_theme:
      - "@EasyAdmin/form/bootstrap_4.html.twig"
      # - "@FOSCKEditor/Form/ckeditor_widget.html.twig"
  list:
    actions:
      - { name: 'show', icon: 'search', label: false }
      - { name: 'edit', icon: 'pencil', label: false }
      - { name: 'delete', icon: 'ban', label: false }
    max_results: 15
  formats:
    date: 'd/m/Y'
    time: 'H:i'
    datetime: 'd/m/Y H:i:s'
  show:
    max_results: 10